title: Fenny Khosla # your name (or website title) here
logo: "/images/mypic.png?raw=true/" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
With a strong academic foundation in Statistics, Mathematics, and Computers, I am passionate about leveraging data to solve complex problems and deliver actionable insights. 

In my previous roles with KPMG, AlixPartners and Capgemini, I worked on market sizing, industry and competitive analysis, and process improvement while applying frameworks like SWOT and Porter’s Five Forces. I also led knowledge management initiatives, including creating SharePoint repositories and leading managing large-scale processes for diverse teams. 

Technical Skills: PostgreSQL, Tableau, Power BI, SharePoint, Python, Internal CRM tool, Internal Communications tool, Microsoft Teams, MS Office (Word, Excel, PowerPoint), Slack, Concur Certification: Python for Data Science, AI & Development from IBM Education: Bachelor of Science (Math, Statistics, Computer Applications), Panjab University, India. Master of Business Administration (Marketing), New Delhi Institute of Management

🔭 Check my portfolio of data analytics projects
📫 If you like my projects, feel free to reach out to me at fenny.khosla@gmail.com
⚡ Fun fact: I once built an excel-based utilization tracker to analyze team productivity, and it not only identified trends but also sparked friendly competition within the office. That’s when I realized data doesn’t just inform decisions—it can inspire people too! <br>

  
  <a href="https://www.linkedin.com/in/fenny-khosla/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
